### ISSUE TITLE
Error on unlock... lock/unlock entity not found

### ISSUE THREAD

**Issue by tnTano** [myhomeiot/DahuaVTO#1]
Hi, i have an issue using component with VTO3211 and VTH5221...
this my configuration:
```
sensor:
  - platform: dahua_vto
    name: CG-Ring
    host: vto_ip
    timeout: 10
    port: 5000
    username: vto_uname
    password: vto_pwd
    scan_interval: 5
#
######################################
#
  - platform: dahua_vto
    name: CG-Phone
    host: vth_ip
    timeout: 10
    port: 5000
    username: vth_uname
    password: vth_pwd
    scan_interval: 5
#
######################################
#
timer:
  door_lock:
    name: Door Lock
    icon: mdi:timer
#
######################################
#
lock:
  - platform: template
    name: CG-Opener
    value_template: "{{ not is_state('timer.door_lock', 'active') }}"
    lock: []
    unlock:
      - service: dahua_vto.open_door
        data_template:
          entity_id: sensor.dahua_vto
          channel: 1
          short_number: HA
#
######################################
#
logger:
  logs:
    custom_components.dahua_vto: debug
#
######################################
#
```
when i click on unlock button i receive this error:

> Failed to call service lock/unlock. entity not found

and on the log:

> 2021-04-21 12:51:10 ERROR (MainThread) [homeassistant.helpers.script.cg_opener] CG-Opener: Error executing script. Error for call_service at pos 1: entity not found
> 2021-04-21 12:51:10 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140658126678432] entity not found
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
>     await handler.job.target(service_call)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
>     await self.hass.helpers.service.entity_service_call(
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
>     future.result()  # pop exception if have
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
>     await result
>   File "/usr/src/homeassistant/homeassistant/components/template/lock.py", line 146, in async_unlock
>     await self._command_unlock.async_run(context=self._context)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1200, in async_run
>     await asyncio.shield(run.async_run())
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
>     await service_task
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
>     await handler.job.target(service_call)
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 719, in admin_handler
>     await result
>   File "/config/custom_components/dahua_vto/__init__.py", line 59, in service_open_door
>     raise HomeAssistantError("entity not found")
> homeassistant.exceptions.HomeAssistantError: entity not found

thanks for the help
