### ISSUE TITLE
Nothing happened after installation and confirmation

### ISSUE THREAD

**Issue by mafelipe16** [myhomeiot/DahuaVTO#10]
I installed from HACS, I checked that custom_component/daue_vto is there, I included this piece in m y configuration.yaml, but no sensor is created....

```
sensor:
  - platform: dahua_vto
    name: Puerta Principal
    host: 192.168.1.47
    username: admin
    password: xxxxxxx
    scan_interval: 5
```

Any help?

The drive is a VTO2211G-WP, wifi connected just installed and working properly as standalone (out of HomeAssistant)

My fault, now is in, don't know what happened..... now I can see:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/64302014/142412432-01771b18-dc52-47df-b787-0ac002a3561d.png">
