### ISSUE TITLE
doorbell

### ISSUE THREAD

**Issue by bisquit2003** [myhomeiot/DahuaVTO#14]
Hello, help the hass newbie, pls. 
I connected dahua vto 2111 to the network (dmss works ok), integrated it into the hass, in sensors dahua vto ok . if I copy the automation completely, different notifications appear every second. So I left only this https://i.postimg.cc/XYJMtZRr/2022-02-13-18-23-47.png
what I want to get - when I press the button on the panel, I want to turn on the doorbell relay for 0,5 sec (or any virtual entity that appears in homekit from hass)

**Comment by myhomeiot** [comment]
Hello, you can use following binary_sensor template for doorbell, it's will `on` when doorbell is ring, but if you want to have it triggered for 0,5 sec you should use the Home Assistant [timer](https://www.home-assistant.io/integrations/timer) like in [door lock example](https://github.com/myhomeiot/DahuaVTO#lock-example-with-call-to-open-door-service).
```
template:
  - trigger:
      - platform: event
        event_type: dahua_vto
        event_data:
          Code: BackKeyLight
    binary_sensor:
      - name: VTO Doorbell
        icon: mdi:doorbell-video
        state: "{{ trigger.event.data.Data.State | int in [1, 2] }}"
```
