### ISSUE TITLE
Playing audio on another machine failed after last update

### ISSUE THREAD

**Issue by Buster14** [myhomeiot/DahuaVTO#15]
```
id: '1640312308566'
alias: Dahua VTO
description: ''
trigger:
  - platform: event
    event_type: dahua_vto
condition:
  - condition: template
    value_template: '{{ trigger.event.data.Data.State | int in [1, 2] }}'
action:
  - service: media_player.media_play
    target:
      entity_id: media_player.gmpc
mode: queued
max: 10
```
So i have GMPC server and GMPC player installed on my viewing station NUC machine, 
The HA is installed on my main server, not the viewing station. The GMPC server's job is to talk to HA in LAN.

On older HA version the above code would trigger doorbell.mp3 on the GMPC player.
But now it wont play at all. I'm getting this error :

> Error: In 'template' condition: UndefinedError: 'dict object' has no attribute 'State'

When trying to execute this part : 

> 
> condition: template
> value_template: '{{ trigger.event.data.Data.State | int in [1, 2] }}'

Any ideas?
Hmm maybe next time i'll think twice before updating HA :(

**Comment by myhomeiot** [comment]
Hello,

You need to filter dahua_vto with Code equals to `BackKeyLight` (another event's which comes from VTO doesn't have field `Data.State`):

```
id: '1640312308566'
alias: Dahua VTO
description: ''
trigger:
  - platform: event
    event_type: dahua_vto
    event_data:
      Code: BackKeyLight
condition:
  - condition: template
    value_template: '{{ trigger.event.data.Data.State | int in [1, 2] }}'
action:
  - service: media_player.media_play
    target:
      entity_id: media_player.gmpc
mode: queued
max: 10
```

**Comment by Buster14** [comment]
That seems to do the trick! Many thanks again @myhomeiot 
Just wondering, was this change caused by home assistant or the plugin?
So next time i will think twice before updating something again.

**Comment by myhomeiot** [comment]
> Just wondering, was this change caused by home assistant or the plugin?
> So next time i will think twice before updating something again.

This was caused by changes in Home Assistant which was introduced in release 2021.10 but until release 2022.2 it's process templates as usual and log the warning, more info about this change you can read [here](https://community.home-assistant.io/t/templating-changes-in-2021-10-0/344173)

Anyway it's good idea to read release notes before update and sometimes check Home Assistant log.

**Comment by Buster14** [comment]
Hi, sorry to reopen this again. Since windows based gmpc is rather unstable, i decided to get sonos play 1. But i cant seem to get this working.
Sonos is detected and i can play audio through media player in HA. I have tried 2 codes :

```
id: '1640312308566'
alias: Dahua VTO
mode: queued
max: 10
description: ''
trigger:
  - platform: event
    event_type: dahua_vto
    event_data:
      Code: BackKeyLight
condition:
  - condition: template
    value_template: '{{ trigger.event.data.Data.State | int in [1, 2] }}'
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.family_room
    data:
      media_content_id: media-source://media_source/local/Doorbell.mp3
```

And the other one :  

```
alias: Dahua VTO
mode: queued
trigger:
- platform: event
  event_type: dahua_vto
  event_data:
    Code: BackKeyLight
action:
- choose:
    - conditions: 
      - condition: template
        value_template: "{{ trigger.event.data.Data.State | int in [1, 2] }}"
      sequence:  
      - service: media_player.play_media
        target:
          entity_id: media_player.family_room
        data:
          media_content_id: media-source://media_source/local/Doorbell.mp3
          media_content_type: audio/mpeg
        metadata:
          title: Doorbell.mp3
          thumbnail: null
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://media_source
  default:
    - service: media_player.play_media
      target:
        entity_id: media_player.family_room
      data:
        media_content_id: media-source://media_source/local/Doorbell.mp3
        media_content_type: audio/mpeg
```

But neither is working, any thoughts?

**Comment by Buster14** [comment]
I managed to run it on the GUI, turn out there's another automation that's preventing it from appearing :  
```
id: '1650994964857'
alias: Dahua-VTO
description: ''
trigger:
  - platform: event
    event_type: dahua_vto
    event_data:
      Code: BackKeyLight
condition:
  - condition: template
    value_template: '''{{ trigger.event.data.Data.State | int in [1, 2] }}'''
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.family_room
    data:
      media_content_id: media-source://media_source/local/Doorbell.mp3
      media_content_type: audio/mpeg
    metadata:
      title: Doorbell.mp3
      thumbnail: null
      media_class: music
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://media_source
mode: queued
```

When i run automation with this, it works, but pressing the doorbell directly hasnt worked yet.. Maybe need action>choose?

**Comment by myhomeiot** [comment]
Latest versions of Home Assistant has [automation debugger](https://www.home-assistant.io/docs/automation/troubleshooting), try to use it in order to understand what happened.

You can remove `mode: queued` or change it to `mode: parallel` maybe first triggered automation stack at service call and other just waiting in the queue, more about automation modes you can read [here](https://www.home-assistant.io/docs/automation/modes).
You get error when you test the condition because `trigger.event.data` defined only when automation triggered by event from Dahua VTO.

**Comment by Buster14** [comment]
Sorry Just got back from a trip to test this again. 
It still doesnt work even with parallel, so i'm not sure which part is causing this,

```
- id: '1650994964857'
  alias: Dahua-VTO
  description: ''
  trigger:
  - platform: event
    event_type: dahua_vto
    event_data:
      Code: BackKeyLight
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.Data.State | int in [1, 2] }}'
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.family_room
    data:
      media_content_id: media-source://media_source/local/Doorbell.mp3
      media_content_type: audio/mpeg
    metadata:
      title: Doorbell.mp3
      thumbnail:
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://media_source
  mode: parallel
```
