### ISSUE TITLE
Door status sensor for channel 2

### ISSUE THREAD

**Issue by damsma** [myhomeiot/DahuaVTO#27]
Hi, how can i get [door status](https://github.com/myhomeiot/DahuaVTO#door-status-sensor-example) for the 2nd channel?

**Comment by myhomeiot** [comment]
Hello,

Maybe you need to use `Index` field, looks like for 1st channel it's `0` for 2nd it's `1`.
If this doesn't helps you need to check full message which you receives from VTO like it's posted [here](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693/116).

```yaml
template:
  - trigger:
      - platform: event
        event_type: dahua_vto
        event_data:
          Code: DoorStatus
          Index: 1
    binary_sensor:
      - name: VTO Door Status
        state: "{{ trigger.event.data.Data.Status | string == 'Open' }}"
        device_class: door
```

**Comment by myhomeiot** [comment]
@damsma Does this helps?

**Comment by damsma** [comment]
@myhomeiot it does not work for me, i turned on debugging and nothing happens in the logs when i trigger the entry gate.

I am using DAHUA DEE1010B-S2 RS485 module.

Is it possible that the VTO is not passing anything from that module? Do you know how to check it?

Opening and closing for the 2nd channel is working fine.

**Comment by myhomeiot** [comment]
@damsma Don't know how this module works but you can dump all events from Dahua VTO using debug logging or this automation:
```yaml
- alias: Dahua VTO All Events
  mode: queued
  trigger:
    - platform: event
      event_type: dahua_vto
  action:
    - service: persistent_notification.create
      data:
        title: "{{ trigger.event.data.Code if trigger.event.data.Code is defined else 'Unknown Code' }}"
        message: "{{ trigger.event.data }}"
```

Do you see events for 2nd channel which works ok?

**Comment by myhomeiot** [comment]
@damsma Does this helps?

**Comment by damsma** [comment]
@myhomeiot the notifications are working, but i can not see any notification for the 2nd channel. 

will double check that the contact sensor is working correctly this weekend.

**Comment by myhomeiot** [comment]
I will close the issue for now. Please let's me know if you found something.

**Comment by myhomeiot** [comment]
I will close the issue for now. Please let's me know if you found something.

**Comment by damsma** [comment]
So today i managed to check the contact sensor, it turned out, the sensor is working fine.

I hooked it up to Home Assistant with an Arduino, so i have the status now available in HA.
My idea is now to use this in an automation in HA to override the status of the Lock, but i am not sure if this is possible?

At the moment it behaves like this:
- the Lock in HA is shown as closed
- when i trigger the Lock in HA, the command is sent and the gate is opened, but the Lock in HA remains in closed position
- trigger the lock again - gate closes - Lock in HA remains in closed position, and so on.

I would like to show the lock as 'open' when the contact sensor changes state, do you think it is possible with an automation?

**Comment by myhomeiot** [comment]
This integration doesn't provide lock entity, instead you need to use lock template in [configuration](https://github.com/myhomeiot/DahuaVTO#lock-example-with-call-to-open-door-service), so you can change behavior of [lock template](https://www.home-assistant.io/integrations/lock.template) and use contact sensor state to change lock state. Here the example where `binary_sensor.door_status2` it's your contact sensor hooked it up to Home Assistant with an Arduino:

```yaml
lock:
  - platform: template
    name: Door Lock
    value_template: "{{ not is_state('binary_sensor.door_status2', 'on') }}"
    optimistic: false
    lock:
      - service: dahua_vto.open_door
        data_template:
          entity_id: sensor.dahua_vto
          channel: 1
          short_number: HA
    unlock:
      - service: dahua_vto.open_door
        data_template:
          entity_id: sensor.dahua_vto
          channel: 1
          short_number: HA
```
