### ISSUE TITLE
time out when call the "dahua_vto.open_door" service

### ISSUE THREAD

**Issue by CatSamaDD** [myhomeiot/DahuaVTO#28]
I have successfully connected to my DAHUA VTO using the plugin, with the model being DH-VTO9531D. After adding the sensor according to the instructions page, the sensor works fine, and the status is displayed as "OK." However, every time I call the "dahua_vto.open_door" service to open the door, I often encounter issues. Specifically, the sensor status changes to "Unavailable," recovers after a few seconds, and prompts a service call timeout. This problem occurs very frequently, significantly affecting normal usage. Could you please take some time to help troubleshoot the issue? Thank you.
![QQ截图20231201202835](https://github.com/myhomeiot/DahuaVTO/assets/34727840/8e56d6ae-c328-48c4-a0b8-64a35bf44637)
[home-assistant.log](https://github.com/myhomeiot/DahuaVTO/files/13526512/home-assistant.log)

**Comment by myhomeiot** [comment]
Hello, 

According the log file you provide (thanks, it's very helpful) the source of the problem it's a call to `accessControl.destroy` (the unlock door it's a sequential call to accessControl.factory.instance, accessControl.openDoor and accessControl.destroy), in your case sometime it's takes around 15 seconds to get reply from VTO.
```
2023-12-01 20:04:33.424 DEBUG (MainThread) [custom_components.dahua_vto.sensor] >>> {"method":"accessControl.destroy","object":58504744,"id":29,"session":368794290}
2023-12-01 20:04:48.725 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":29,"result":true,"session":368794290}

2023-12-01 20:04:56.647 DEBUG (MainThread) [custom_components.dahua_vto.sensor] >>> {"method":"accessControl.destroy","object":58504744,"id":35,"session":368794290}
2023-12-01 20:05:11.755 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":35,"result":true,"session":368794290}
```

The command `dahua_vto.open_door` has timeout parameter, by default it's 5 seconds and usually it's more than enough. You can change timeout to 20 and this should solve your problem.
```yaml
- service: dahua_vto.open_door
  data_template:
    entity_id: sensor.dahua_vto
    channel: 1
    short_number: HA
    timeout: 20

```

But I suggest you also to check maybe your VTO has newer firmware and update will fix this issue.
Hopes this helps. Let's me know that you find.

**Comment by CatSamaDD** [comment]
Thank you. However, a response time of around 15 seconds is indeed a bit too long for home automation. I have found a project based on MQTT forwarding at https://gitlab.com/elad.bar/DahuaVTO2MQTT. This project seems to use the API "/cgi-bin/accessControl.cgi?action=openDoor&UserID=101&Type=Remote&channel=" for the "opendoor" operation. I tried using this project for "opendoor" and found almost no delay or response timeout issues. Perhaps, this could be a better solution for dahuavto "opendoor." ?

**Comment by myhomeiot** [comment]
When you specify timeout for `dahua_vto.open_door` command it's will affect only this command and all other communication like notification from VTO, another open door commands, etc will works as usual. API for open door in my case works worse but you can use this API call even without any other integrations by `shell_command`, for example:
```yaml
shell_command:
  curl: "/usr/bin/curl {{ command }}"

lock:
  - platform: template
    name: Door Lock
    value_template: "{{ not is_state('timer.door_lock', 'active') }}"
    optimistic: false
    lock:
    unlock:
      - service: shell_command.curl
        data_template:
          command: "--insecure --digest --get https://192.168.1.101/cgi-bin/accessControl.cgi?action=openDoor&UserID=101&Type=Remote&channel=1"
```

If [DahuaVTO2MQTT](https://gitlab.com/elad.bar/DahuaVTO2MQTT) integration works better for you - use it instead.
You can also try to use [this](https://github.com/rroller/dahua) integration, AFAIK it's use part of my code for doorbell and open door in same way as my integration.
You can also keep using my integration but open the door using shell command like in example.
Hopes this helps.
