### ISSUE TITLE
emulate doorbell button press

### ISSUE THREAD

**Issue by bartoszx** [myhomeiot/DahuaVTO#30]
Hello 
I am finishing integration with custom device to read barcode and open gate if code is available in database.
I want to virtualy press ring button if barcode is not available in database.
Can you show some example?

**Comment by bartoszx** [comment]
Thank you for your response. Yes, I want to send a command to the VTO to simulate pressing the doorbell button, causing it to make a SIP call just as it would if the physical ring button were pressed. The scenario is as follows:

When a barcode is scanned and found to be invalid (i.e., not in the database), I want Home Assistant to virtually press the ring button on the VTO so that the courier will be able to call through the intercom as if they pressed the button physically.

**Comment by myhomeiot** [comment]
Don't know if it possible at all but I will try to find something.

**Comment by myhomeiot** [comment]
I found the command which working with my VTO2111D! It's make a SIP call to number 9901 same as doorbell button. To cancel the call you can use `hc` command.

```yaml
service: dahua_vto.send_command
data:
  entity_id: sensor.dahua_vto
  method: console.runCmd
  params: {'command': 'call 9901'}
  event: false
```
