### ISSUE TITLE
Set Config on VTO4202F-P-S2

### ISSUE THREAD

**Issue by THorst92** [myhomeiot/DahuaVTO#38]
Hello all,

I have a problem with my VTO4202F-P-S2 and maybe someone can help me.
I want to change the speaker volume in the config and used this statement:
```
action: dahua_vto.send_command
data:
  entity_id: sensor.dahua_vto
  method: configManager.setConfig
  params: {'table': {'AudioOutputVolume': [100,60]}, 'name': 'CommGlobal'}
  event: false
```
I receive the following event:
```
event_type: dahua_vto
data:
  AudioOutputVolume:
    - 10
    - 60
  entity_id: sensor.dahua_vto
  Code: client.notifyConfigChange
origin: LOCAL
time_fired: "*****"
context:
  id: *****
  parent_id: null
  user_id: null
```
But neither on the webpage nor in the dahua console the parameter was changed, also the volume itself does not change.
Does anybody have an idea why this could happened, or where to search for an issue?

Best regards

**Comment by myhomeiot** [comment]
Hello,

If you set `AudioOutputVolume`, why you use `'name': 'CommGlobal'`?

The command should look like (for my VTO it's change the Beep Volume to 100):
```yaml
service: dahua_vto.send_command
data:
  entity_id: sensor.dahua_vto
  method: configManager.setConfig
  params: {'table': [100, 60], 'name': 'AudioOutputVolume'}
  event: true
```
