### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by bulava92** [myhomeiot/DahuaVTO#39]
<img width="495" alt="Снимок экрана 2025-01-04 в 10 54 57" src="https://github.com/user-attachments/assets/dc817660-95d1-4258-990b-de33b9963847" />

Hello

Can you tell me how I can disable all notifications except data? Because there are 500-600 of them in a day

And another question, if a call comes from an external panel, when you open a lock from home assistant, is it possible to do something so that the call is reset? If so, how?

**Comment by myhomeiot** [comment]
Hello,

Notification used for debug purposes, if you have everything working you can remove or disable `Dahua VTO All Events` automation which is make this notifications by calling `service: persistent_notification.create` (if you take configuration examples from README) or comment call to `persistent_notification.create` in another automation which receives event from VTO.

You can cancel the call using example from [here](https://github.com/myhomeiot/DahuaVTO#some-command-examples), call it just after or before opening lock:
```yaml
# Cancel VTO Call
service: dahua_vto.send_command
data:
  entity_id: sensor.dahua_vto
  method: console.runCmd
  params: {'command': 'hc'}
  event: false
```

Please use the [forum](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693) in the future for such questions.
