### ISSUE TITLE
ASI6214S (-PW) Support

### ISSUE THREAD

**Issue by Onepamopa** [myhomeiot/DahuaVTO#41]
Hello,

I tried using your integration on this device, but it doesn't seem it has port 5000 open at all.
What would you need to be able to add support for the device? I can provide you access to a device and do testing.

**Comment by myhomeiot** [comment]
Hello,

Some times the port of DHIP protocol can be **37777**, more details [here](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693/378)
You can try to get the correct port from Dahua DMSS application.

If you familiar with Python you can try to use [this](https://github.com/mcw0/Tools) console application and check if it's can connect and get the data, this application support not just DHIP protocol so you need to try different protocols as well.

Why you looking for this device support in this integration, do you have experience with this integration and another device?

**Comment by Onepamopa** [comment]
No experience, I just got these devices along with a DSS Express server & the appropriate licenses.
I was looking for an easy way to integrate them into HA - when the door bell is pressed & to be able to unlock the door(s).

Will look into the app you suggested. -- Which of the two are you referring to?
Dahua-JSON-Debug-Console-v2.py -- """
2021-10-06
This project is obsolete: Please go to https://github.com/mcw0/DahuaConsole
"""

**Comment by myhomeiot** [comment]
> Will look into the app you suggested. -- Which of the two are you referring to?

Yes, this [one](https://github.com/mcw0/DahuaConsole) should work.

Meanwhile you can control door lock using http call from example [here](https://github.com/myhomeiot/DahuaVTO/issues/28#issuecomment-1837114976)

By first check the port by DMSS application and try to change port to 37777 it's can work as well.

**Comment by myhomeiot** [comment]
@Onepamopa Any news?

**Comment by myhomeiot** [comment]
@Onepamopa Let's me know when you get any news. Meanwhile I will close this issue, but if you get something to work I will reopen it again.

**Comment by Onepamopa** [comment]
I'll be at the location next week, then I'd be able to test.

**Comment by myhomeiot** [comment]
> I'll be at the location next week, then I'd be able to test.

Great! Looking forward for the update.

**Comment by myhomeiot** [comment]
@Onepamopa Let's me know when you get any news. Meanwhile I will close this issue, but if you get something to work I will reopen it again.

**Comment by DrSpaldo** [comment]
I know this is an old issue but I just wanted to say thanks @myhomeiot . I got this working with my ASI6214S-PW & ASI7214S-W. I am still trying to get as many additional sensors as I can find up & running but so far I can unlock & see if my door is open/closed.

**Comment by Onepamopa** [comment]
> I know this is an old issue but I just wanted to say thanks [@myhomeiot](https://github.com/myhomeiot) . I got this working with my ASI6214S-PW & ASI7214S-W. I am still trying to get as many additional sensors as I can find up & running but so far I can unlock & see if my door is open/closed.

how?

**Comment by DrSpaldo** [comment]
@Onepamopa is anything working?  This is what I have for the basic settings..

configuration.yaml
```
timer:
  door_lock:
    name: Door Lock
    icon: mdi:timer
    
sensor:
  - platform: dahua_vto
    name: Dahua VTO Front Door
    host: 192.168.1.143
    username: USERNAME
    password: PASS
    scan_interval: 5
```

*note the above username/pass is one of the users in the Dahua Web GUI. System -> Account

```
template:
- trigger:
    - platform: event
      event_type: dahua_vto
      event_data:
        Code: DoorStatus
  binary_sensor:
    - name: Front Door Status
      unique_id: front_door_status
      device_class: door
      state: >
        {{ trigger.event.data.Data.Status | string == 'Open' }}

- lock:
    - name: Front Door Lock
      unique_id: front_door_lock
      state: >
        {{ 'unlocked' if is_state('binary_sensor.front_door_status', 'on') else 'locked' }}
      icon: >
        {{ 'mdi:lock-open-variant' if is_state('binary_sensor.front_door_status', 'on') else 'mdi:lock' }}
      unlock:
        - action: dahua_vto.open_door
          data:
            entity_id: sensor.dahua_vto_front_door
            channel: 1
            short_number: HA
      lock:
        - action: homeassistant.update_entity
          target:
            entity_id: sensor.dahua_vto_front_door
```

Also check these in the Dahua Web GUI:
- Intercom Settings -> SIP Server -> Turned on? 
- Intercom Settings -> Device setting -> Does 'VTO' say "online"
