### ISSUE TITLE
unable to use different name for the lock entity

### ISSUE THREAD

**Issue by hossamnagy** [myhomeiot/DahuaVTO#44]
Is the entity name lock.door_lock hard coded ?

Following the configuration examples I was able to create a lock and unlock the door from home assistant. 
When I  change the lock entity name to be lock.frontdoorlock   I get an error in the log unable to reference entity lock.frontdoorlock

Thanks

**Comment by myhomeiot** [comment]
Hello,

If you use example from [readme](https://github.com/myhomeiot/DahuaVTO#lock-example-with-call-to-open-door-service) check comment:

```yaml
lock:
  - platform: template
    name: Door Lock # <--- Here the name which becomes lock.door_lock, if you want frontdoorlock - change it to frontdoorlock 
    ...
```
