### ISSUE TITLE
VTO2000 Event Unlock for Card and Fingerprint

### ISSUE THREAD

**Issue by dreitakter** [myhomeiot/DahuaVTO#5]
Hi, 

I own a Dahua VTO2000 and your Integration works basicly.

I have not connected my Door-Opener directly to the VTO2000.
The Door-Opener is a binary switch in HA and works with an relay.

Because of that I need an Event "Access granted" everytime a valid Fingerprint or valid ID-Card is recognized from the Dahua VTO.

First Step -> Simple Event when access is granted

Second Step -> Complex Event when access is granted including which ID triggered the access (example: my fingerprint -> ID 1 unlocked the door    ---  fingerprint of child -> ID 2 unlocked the door) if this is possible

I habe setup some ID-Cards for testing.

What are the next steps? Which information do you need to implement this?

Thanks for your work in this great project :)

I habe activated logging
Here is something from the Logs:
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] Connecting blablabla:5000, username blablabla
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] >>> {"method":"global.login","params":{"clientType":"","ipAddr":"(null)","loginType":"Direct"},"id":1,"session":0}
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"error":{"code":268632079,"message":"Component error: login challenge!"},"id":1,"params":{"authorization":"blablabla","encryption":"Default","mac":"38AF29BF4B14","random":"blablabla","realm":"Login to blablabla"},"result":false,"session":2147473615}
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] >>> {"method":"global.login","params":{"clientType":"","ipAddr":"(null)","loginType":"Direct","userName":"admin","password":"blablabla"},"id":2,"session":2147473615}
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":2,"params":{"keepAliveInterval":60},"result":true,"session":2147473615}
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] >>> {"method":"eventManager.attach","params":{"codes":["All"]},"id":3,"session":2147473615}
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] >>> {"method":"magicBox.getSystemInfo","id":4,"session":2147473615}
2021-08-06 14:32:49 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook ba3b4414c2d017d47f6967ea21db00712d5155b53e0d0737b9f08fe1f2e4d73b from 192.168.178.41
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":3,"params":{"SID":513},"result":true,"session":2147473615}
2021-08-06 14:32:49 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":4,"params":{"appAutoStart":true,"deviceType":"VTO2000A","hardwareVersion":"1.00","processor":"dm365","serialNumber":"4G05C25PAZD71F4","updateSerial":"VTO2000A","updateSerialCloudUpgrade":"VTO2000A:0:4:1:3:5:0:1:9:3:3:0:1B0:0:0:0:0:0:0:0"},"result":true,"session":2147473615}
2021-08-06 14:32:50 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< **{"id":3,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"**Action":"Start","Code":"AddCard","Data":{"Data":[{"CardNo":"3D609DA1","CardStatus":0,"CardType":0,"UserID":"1405","UserName":"SK-Work"}],"LocaleTime":"2021-08-06 12:30:53","Name":"Card","Number":1**"UTC":1628253053.0}**,"Index":0,"Param":null},{"Action":"Start","Code":"AlarmLocal","Data":{"LocaleTime":"2021-08-06 12:30:53","UTC":1628253053.0},"Index":1,"Param":{}},{"Action":"Start","Code":"CallNoAnswered","Data":{"CallID":"0","IsEncryptedStream":false,"LocaleTime":"2021-08-06 12:30:53","LockNum":2,"SupportPaas":false,"TCPPort":37777,"UTC":1628253053.0},"Index":9900,"Param":{}},{"Action":"Start","Code":"ProfileAlarmTransmit","Data":{"DevSrcType":"Digit","LocaleTime":"2021-08-06 12:30:53","SenseMethod":"PreventRemove","UTC":1627956090,"UserID":"8001"},"Index":1,"Param":null},{"Action":"Start","Code":"RtspSessionDisconnect","Data":{"Device":"192.168.178.56","LocaleTime":"2021-08-06 12:30:53","StreamType":"Extra1","UTC":1628253053.0,"UserAgent":" Lavf58.20.100"},"Index":0,"Param":null},{"Action":"Start","Code":"_FingerPrintCollect_","Data":{"FingerPrintName":"pk","LocaleTime":"2021-08-06 12:30:53","UTC":1628253053.0,"UserID":"1405"},"Index":0,"Param":null}]},"session":2147473615}
2021-08-06 14:36:28 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":3,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"BackKeyLight","Data":{"LocaleTime":"2021-08-06 12:34:31","State":8,"UTC":1628253271.0},"Index":-1}]},"session":2147473615}
2021-08-06 14:36:28 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":3,"method":"client.notifyEventStream","params":{"SID":513,"eventList":[{"Action":"Pulse","Code":"AccessControl","Data":{"CardNo":"bd08f6fa","CardType":null,"LocaleTime":"2021-08-06 **12:34:31","Method":1,"Name":"OpenDoor","Password":"","ReaderID":"1","RecNo":4,"SnapURL":"","Status":1,"Type":"Entry","UTC":1628253271.0,"UserID":"1405"},"Index":0}]},"session":2147473615}**
2021-08-06 14:36:50 DEBUG (MainThread) [custom_components.dahua_vto.sensor] >>> {"method":"global.keepAlive","params":{"timeout":60,"action":true},"id":8,"session":2147473615}
2021-08-06 14:36:50 DEBUG (MainThread) [custom_components.dahua_vto.sensor] <<< {"id":8,"params":{"timeout":60},"result":true,"session":2147473615}

**Comment by myhomeiot** [comment]
This integration basically receives all events from VTO and pass it to Home Assistant.

As I see from the log you already have events when you use the card in order to open door. You can use event with Code = AccessControl, Name = OpenDoor and Status = 1 in Home Assistant automation as access granted event, and distinguish users by UserID.

For example:
```
- alias: Dahua VTO AccessControl
  mode: queued
  trigger:
    - platform: event
      event_type: dahua_vto
      event_data:
        Code: AccessControl
  action:
    - choose:
        - conditions: >
            {{ trigger.event.data.Data.Name == 'OpenDoor' and trigger.event.data.Data.Status | int == 1 }}
          sequence:
            - service: persistent_notification.create
              data:
                title: "Access Granted for UserID {{ trigger.event.data.Data.UserID | int }}"
                message: "{{ trigger.event.data }}"
      default:
        - service: persistent_notification.create
          data:
            title: "AccessControl Event"
            message: "{{ trigger.event.data }}"
```
